name: covid19mobile
description: COVID19 App

version: 1.0.2+12

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  youtube_player_flutter: ^6.1.0+4
  flutter:
    sdk: flutter
  
  # Internalization
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  intl: 0.16.1 

  # Services
  dio: 3.0.9
  logger: 0.8.3
  url_launcher: ^5.4.2
  notification_permissions: 0.4.4
  app_settings: ^3.0.1

  # App
  cupertino_icons: 0.1.2
  provider: 4.0.4
  rxdart: 0.23.1
  html: 0.14.0+3
  flutter_html: 0.11.1
  fl_chart: 0.10.1


  # Firebase
  firebase_core: ^0.5.0+1 
  # For the FlutterFire plugin for Google Analytics
  firebase_analytics: 6.1.0
  # Firebase Crashlytics  
  firebase_crashlytics: 0.2.2
  # Firebase Messaging 
  firebase_messaging: 7.0.3
  # Firebase Firestore
  cloud_firestore: 0.14.1+3

  # UI
  google_fonts: 0.3.10
  flare_flutter: 2.0.1

  json_annotation: ^3.0.0

  # Svg
  flutter_svg: 0.20.0-nullsafety.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1
  build_runner: ^1.10.0
  built_value_generator: ^8.0.4
  flutter_native_splash: ^0.3.0
  json_serializable: ^3.5.1


dependency_overrides:
  intl: 0.17.0
  path_drawing: ^0.5.0-nullsafety.0
  xml: ^5.0.0-nullsafety.0
  # analyzer: 0.39.14 


flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/licence.txt

flutter_intl:
  enabled: true
